modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/itsmeow/QuickSpawns/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/quickspawns"
logoFile="quickspawns.png"
credits="itsmeowdev, for programming, ideas, design, and leading"
authors="itsmeowdev"
[[mods]]
modId="quickspawns"
version="${version}"
displayName="QuickSpawns"
description='''
This mod adds a quick and easy way to set spawns with /setspawn and /spawn'''
[[dependencies.quickspawns]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="SERVER"